name: jk_teleport
version: '${project.version}'
main: jiekie.TeleportPlugin
api-version: '1.20'
authors: [Jiekie]
description: 텔레포트 플러그인
depend: [jk_nickname]
softdepend:
  - jk_multi_world
commands:
  텔레포트:
    description: 텔레포트 관련 명령어
    usage: /텔레포트
    tab-completer: jiekie.completer.TeleportTabCompleter
    permission: jk.teleport.command
    permission-message: ''
